services:
  - type: web
    name: ivoirerental
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @workspace/ivoir-rental run build && pnpm --filter @workspace/api-server run build
    startCommand: node --enable-source-maps artifacts/api-server/dist/index.mjs
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
